window.MirabentTranslations = {
  ca: {
    'Edició actual':'Edició actual','Història':'Història','Multimèdia':'Multimèdia','Contacte':'Contacte','Inscripcions':'Inscripcions','Inici':'Inici',
    'Sitges · Catalunya':'Sitges · Catalunya','30 Concurs ':'30 Concurs ','Josep Mirabent i Magrans':'Josep Mirabent i Magrans',
    'Concurs internacional de música clàssica que posa al centre els intèrprets i ofereix als joves músics un espai per créixer, donar-se a conèixer i avançar en el seu camí professional.':'Concurs internacional de música clàssica que posa al centre els intèrprets i ofereix als joves músics un espai per créixer, donar-se a conèixer i avançar en el seu camí professional.',
    'Consultar l\'edició actual':'Consultar l\'edició actual','Tota la informació de la convocatòria actual: bases, dates, proves, premis, lloc i jurat.':'Tota la informació de la convocatòria actual: bases, dates, proves, premis, lloc i jurat.',
    'Música de cambra i Cant':'Música de cambra i Cant','Informació bàsica i calendari de modalitats.':'Informació bàsica i calendari de modalitats.','El concurs':'El concurs','Música,':'Música,','talent i trajectòria':'talent i trajectòria',
    'El Concurs Josep Mirabent i Magrans està dedicat a la música clàssica i posa els intèrprets al centre. La seva vocació és reconèixer la qualitat artística i, especialment, oferir als joves músics una oportunitat per donar a conèixer el seu talent, ampliar la seva projecció i continuar desenvolupant la seva trajectòria professional.':'El Concurs Josep Mirabent i Magrans està dedicat a la música clàssica i posa els intèrprets al centre. La seva vocació és reconèixer la qualitat artística i, especialment, oferir als joves músics una oportunitat per donar a conèixer el seu talent, ampliar la seva projecció i continuar desenvolupant la seva trajectòria professional.',
    'Jurat · Edició 2026':'Jurat · Edició 2026','Els membres del jurat':'Els membres del jurat','Composició actual del jurat de 2026. Les fotografies dels membres s\'afegiran quan estiguin disponibles.':'Composició actual del jurat de 2026. Les fotografies dels membres s\'afegiran quan estiguin disponibles.',
    'Música de cambra':'Música de cambra','Cant':'Cant','Director d\'orquestra i compositor':'Director d\'orquestra i compositor','Pianista i compositora':'Pianista i compositora','Violinista':'Violinista','Musicòleg':'Musicòleg','Cantant':'Cantant','Nom a confirmar':'Nom a confirmar','Càrrec pendent':'Càrrec pendent','Foto del membre':'Foto del membre',
    'Veure l\'historial del jurat →':'Veure l\'historial del jurat →','Trajectòria':'Trajectòria','La història del concurs':'La història del concurs','Tres dècades de música, d\'intèrprets i de trobades artístiques que han consolidat el concurs com un espai de descoberta i projecció del talent.':'Tres dècades de música, d\'intèrprets i de trobades artístiques que han consolidat el concurs com un espai de descoberta i projecció del talent.','Coneix la història':'Coneix la història','El concurs en imatges':'El concurs en imatges','Fotografies':'Fotografies','Participa':'Participa','La inscripció continuarà fent-se per correu electrònic. Les instruccions i la documentació de la convocatòria es mostraran aquí.':'La inscripció continuarà fent-se per correu electrònic. Les instruccions i la documentació de la convocatòria es mostraran aquí.','Veure inscripcions':'Veure inscripcions','Email':'Email','Telèfon':'Telèfon','Adreça':'Adreça','Instagram':'Instagram','Facebook':'Facebook',
    'Sitges · Catalunya':'Sitges · Catalunya'
  },
  es: {
    'Edició actual':'Edición actual','Història':'Historia','Multimèdia':'Multimedia','Contacte':'Contacto','Inscripcions':'Inscripciones','Inici':'Inicio',
    'Sitges · Catalunya':'Sitges · Cataluña','30 Concurs ':'30 Concurso ','Josep Mirabent i Magrans':'Josep Mirabent i Magrans',
    'Concurs internacional de música clàssica que posa al centre els intèrprets i ofereix als joves músics un espai per créixer, donar-se a conèixer i avançar en el seu camí professional.':'Concurso internacional de música clásica que pone a los intérpretes en el centro y ofrece a los jóvenes músicos un espacio para crecer, darse a conocer y avanzar en su trayectoria profesional.',
    'Consultar l\'edició actual':'Consultar la edición actual','Tota la informació de la convocatòria actual: bases, dates, proves, premis, lloc i jurat.':'Toda la información de la convocatoria actual: bases, fechas, pruebas, premios, lugar y jurado.',
    'Música de cambra i Cant':'Música de cámara y Canto','Informació bàsica i calendari de modalitats.':'Información básica y calendario de modalidades.','El concurs':'El concurso','Música,':'Música,','talent i trajectòria':'talento y trayectoria',
    'El Concurs Josep Mirabent i Magrans està dedicat a la música clàssica i posa els intèrprets al centre. La seva vocació és reconèixer la qualitat artística i, especialment, oferir als joves músics una oportunitat per donar a conèixer el seu talent, ampliar la seva projecció i continuar desenvolupant la seva trajectòria professional.':'El Concurso Josep Mirabent i Magrans está dedicado a la música clásica y pone a los intérpretes en el centro. Su vocación es reconocer la calidad artística y, especialmente, ofrecer a los jóvenes músicos una oportunidad para dar a conocer su talento, ampliar su proyección y continuar desarrollando su trayectoria profesional.',
    'Jurat · Edició 2026':'Jurado · Edición 2026','Els membres del jurat':'Los miembros del jurado','Composició actual del jurat de 2026. Les fotografies dels membres s\'afegiran quan estiguin disponibles.':'Composición actual del jurado de 2026. Las fotografías de los miembros se añadirán cuando estén disponibles.',
    'Música de cambra':'Música de cámara','Cant':'Canto','Director d\'orquestra i compositor':'Director de orquesta y compositor','Pianista i compositora':'Pianista y compositora','Violinista':'Violinista','Musicòleg':'Musicólogo','Cantant':'Cantante','Nom a confirmar':'Nombre por confirmar','Càrrec pendent':'Cargo pendiente','Foto del membre':'Foto del miembro',
    'Veure l\'historial del jurat →':'Ver el historial del jurado →','Trajectòria':'Trayectoria','La història del concurs':'La historia del concurso','Tres dècades de música, d\'intèrprets i de trobades artístiques que han consolidat el concurs com un espai de descoberta i projecció del talent.':'Tres décadas de música, de intérpretes y de encuentros artísticos que han consolidado el concurso como un espacio de descubrimiento y proyección del talento.','Coneix la història':'Conoce la historia','El concurs en imatges':'El concurso en imágenes','Fotografies':'Fotografías','Participa':'Participa','La inscripció continuarà fent-se per correu electrònic. Les instruccions i la documentació de la convocatòria es mostraran aquí.':'La inscripción continuará realizándose por correo electrónico. Las instrucciones y la documentación de la convocatoria se mostrarán aquí.','Veure inscripcions':'Ver inscripciones','Email':'Email','Telèfon':'Teléfono','Adreça':'Dirección','Instagram':'Instagram','Facebook':'Facebook'
  },
  en: {
    'Edició actual':'Current edition','Història':'History','Multimèdia':'Multimedia','Contacte':'Contact','Inscripcions':'Registration','Inici':'Home',
    'Sitges · Catalunya':'Sitges · Catalonia','30 Concurs ':'30th Competition ','Josep Mirabent i Magrans':'Josep Mirabent i Magrans',
    'Concurs internacional de música clàssica que posa al centre els intèrprets i ofereix als joves músics un espai per créixer, donar-se a conèixer i avançar en el seu camí professional.':'International classical music competition placing performers at the centre and offering young musicians a space to grow, gain recognition and advance their professional careers.',
    'Consultar l\'edició actual':'View current edition','Tota la informació de la convocatòria actual: bases, dates, proves, premis, lloc i jurat.':'All the information about the current competition: rules, dates, rounds, prizes, venue and jury.',
    'Música de cambra i Cant':'Chamber Music and Singing','Informació bàsica i calendari de modalitats.':'Basic information and schedule for both categories.','El concurs':'The competition','Música,':'Music,','talent i trajectòria':'talent and trajectory',
    'El Concurs Josep Mirabent i Magrans està dedicat a la música clàssica i posa els intèrprets al centre. La seva vocació és reconèixer la qualitat artística i, especialment, oferir als joves músics una oportunitat per donar a conèixer el seu talent, ampliar la seva projecció i continuar desenvolupant la seva trajectòria professional.':'The Josep Mirabent i Magrans Competition is dedicated to classical music and places performers at the centre. Its mission is to recognise artistic excellence and, especially, to give young musicians an opportunity to showcase their talent, broaden their profile and continue developing their professional careers.',
    'Jurat · Edició 2026':'Jury · 2026 edition','Els membres del jurat':'Jury members','Composició actual del jurat de 2026. Les fotografies dels membres s\'afegiran quan estiguin disponibles.':'Current composition of the 2026 jury. Members’ photographs will be added when available.',
    'Música de cambra':'Chamber Music','Cant':'Singing','Director d\'orquestra i compositor':'Conductor and composer','Pianista i compositora':'Pianist and composer','Violinista':'Violinist','Musicòleg':'Musicologist','Cantant':'Singer','Nom a confirmar':'To be confirmed','Càrrec pendent':'Role pending','Foto del membre':'Member photo',
    'Veure l\'historial del jurat →':'View jury history →','Trajectòria':'Journey','La història del concurs':'The history of the competition','Tres dècades de música, d\'intèrprets i de trobades artístiques que han consolidat el concurs com un espai de descoberta i projecció del talent.':'Three decades of music, performers and artistic encounters that have established the competition as a space for discovering and supporting talent.','Coneix la història':'Discover the history','El concurs en imatges':'The competition in pictures','Fotografies':'Photography','Participa':'Take part','La inscripció continuarà fent-se per correu electrònic. Les instruccions i la documentació de la convocatòria es mostraran aquí.':'Registration will continue to be completed by email. Instructions and competition documents will be provided here.','Veure inscripcions':'View registration','Email':'Email','Telèfon':'Phone','Adreça':'Address','Instagram':'Instagram','Facebook':'Facebook'
  }
};